name: ocrmypdf # you probably want to 'snapcraft register <name>'
title: ocrmypdf
base: core20 # the base snap is the execution environment for this snap
version: '1.1.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Hobby Project Snap for the Python Program "OCRmyPDF" by James R. Barlow
description: OCRmyPDF by James R. Barlow
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures: [amd64]

environment:
    TESSDATA_PREFIX: $SNAP/usr/share/tesseract-ocr/4.00/tessdata
    GS_LIB: $SNAP/usr/share/ghostscript/9.50/Resource/Init
    GS_FONTPATH: $SNAP/usr/share/ghostscript/9.50/Resource/Font
    LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu

apps:
  ocrmypdf:
    command: usr/bin/snapcraft-preload python3 -m ocrmypdf
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - removable-media

parts:
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr -DLIBPATH=/usr/lib
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
    stage-packages:
      - lib32stdc++6

  ocrmypdf:
    # See 'snapcraft plugins'
    plugin: python
    source: https://github.com/ocrmypdf/OCRmyPDF.git

    stage-packages:
      - ghostscript
      - icc-profiles-free
      - liblept5
      - libxml2
      - pngquant
      - tesseract-ocr-all
      - unpaper
      - qpdf
      - zlib1g

    python-packages:
#      - ocrmypdf
      - cffi  # must be a setup and install requirement
      - pdfminer.six
      - pikepdf
      - Pillow
      - pluggy
      - reportlab
      - setuptools
      - tqdm
      - pipe

    override-build: |
      snapcraftctl build
      ln -sf ../usr/lib/libsnapcraft-preload.so $SNAPCRAFT_PART_INSTALL/lib/libsnapcraft-preload.so
